### PR TITLE
Added dependency note on cairo.

### LINKED ISSUE #60: Dependency on cairo and xcb-shm
I attempted to install brain using `npm install`, and I got the following error.

```
Perhaps you should add the directory containing `cairo.pc'
to the PKG_CONFIG_PATH environment variable
No package 'cairo' found
```

So, I attempted to install [cairo](http://cairographics.org/), but there also appears to be a dependency upon xcb-shm. I think this may be cairo's dependency. In my case, on a Mac, I attempted to install cairo using homebrew.

At any rate, perhaps the installation instructions could be expanded to include cairo installation, since it's non-obvious? I'll be happy to send a PR if I get it working, but if somebody has already done this successfully, I'd really appreciate some pointers.

### PR DESCRIPTION
**Pull request by johnmarkos**
Fixes #60

### CODE REVIEW

**Comment by robertleeplummerjr** [comment]
Would you consider closing this here, and reopening at: https://github.com/harthur-org/brain.js/pulls?

If so, we could add you as a collaborator.

**Comment by robertleeplummerjr** [comment]
good things coming? ;)

**Comment by johnmarkos** [comment]
Here you go. https://github.com/BrainJS/brain.js/pull/215

**Comment by robertleeplummerjr** [comment]
ty ty

**Pull request closed without merging**
